import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { checkout } from "../checkout";

const Home: NextPage = () => {
  const handleCheckout = () => {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy my art work </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/art-1.jpg" width={600} height={600} />
            <h2>Shona Lisa</h2>
            <button
              onClick={() => {
                checkout({
                  lineItems: [
                    { price: "price_1L7Du8DlXeCDkklrstcPylH4", quantity: 1 },
                  ],
                });
              }}
            >
              BUY NOW!
            </button>
          </div>

          <div className={styles.card}>
            <Image src="/art-2.jpg" width={600} height={600} />
            <h2>Majnoo Bhai</h2>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
