import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy my art work </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Image src="/art-1.jpg" width={600} height={600} />
            <h2>Shona Lisa</h2>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <Image src="/art-2.jpg" width={600} height={600} />
            <h2>Majnoo Bhai</h2>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
