const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 100,
      countInStock: 50,
      description: "The best free shirt available",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 90,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 50,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 50,
      brand: "Raymond",
      rating: 4.7,
      numReviews: 500,
      countInStock: 5,
      description: "The slimmest shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 60,
      brand: "Plyer",
      rating: 4.1,
      numReviews: 150,
      countInStock: 80,
      description: "The golf pants you never imagined",
    },
    {
      name: "Shady Pants",
      slug: "shady-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 60,
      brand: "Slimshady",
      rating: 4.8,
      numReviews: 350,
      countInStock: 8,
      description: "Be the next slim shady with these pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 360,
      brand: "Zara",
      rating: 4.9,
      numReviews: 3500,
      countInStock: 5,
      description: "The pants for the fashionista inside you",
    },
  ],
};

export default data;
